// RESULTS
export const RESET_RESULTS = 'RESET_RESULTS';
export const GET_RESULTS = 'GET_RESULTS';
export const GET_RESULT = 'GET_RESULT';
export const FETCH_RESULTS = 'FETCH_RESULTS';
export const RESULTS_ERROR = 'RESULTS_ERROR';

// CATEGORIES
export const RESET_CATEGORIES = 'RESET_CATEGORIES';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const CATEGORIES_ERROR = 'CATEGORIES_ERROR';