// RESULTS
export const RESET_RESULTS = 'RESET_RESULTS';
export const GET_RESULTS = 'GET_RESULTS';
export const GET_RESULT = 'GET_RESULT';
export const FETCH_RESULTS = 'FETCH_RESULTS';
export const RESULTS_ERROR = 'RESULTS_ERROR';

// CATEGORIES
export const RESET_CATEGORIES = 'RESET_CATEGORIES';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const CATEGORIES_ERROR = 'CATEGORIES_ERROR';

// MAPS
export const RESET_MAPS = 'RESET_MAPS';
export const FOCUS_MARKER = 'FOCUS_MARKER';

// PAGINATION
export const RESET_PAGINATION = 'RESET_PAGINATION';
export const SET_PAGE = 'SET_PAGE';
export const SET_OFFSET = 'SET_OFFSET';
export const SET_PERPAGE = 'SET_PERPAGE';